AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: MsdTaskFamily
      Cpu: 1024
      Memory: 2048
      NetworkMode: bridge
      RequiresCompatibilities:
        - EC2
      ExecutionRoleArn: arn:aws:iam::227868074243:role/ecsTaskExecutionRole
      RuntimePlatform:
        OperatingSystemFamily: LINUX
        CpuArchitecture: X86_64
      ContainerDefinitions:
        - Name: msdContainer
          Cpu: 0
          Image: public.ecr.aws/r4l7l0a2/msd:latest
          PortMappings:
            - ContainerPort: 5000
              HostPort: 5000
              Protocol: tcp
              AppProtocol: http
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: true
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: containerlog
  ServiceDefinition:
    Type: AWS::ECS::Service
    Properties:
      Cluster: arn:aws:ecs:eu-central-1:227868074243:cluster/test-app
      LaunchType: EC2
      TaskDefinition: !Ref TaskDefinition
      ServiceName: msdService

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /msdTask

  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ ecs-tasks.amazonaws.com ]
            Action: [ 'sts:AssumeRole' ]
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy