AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM base template for 
  Flask Bitcoin microservice

Resources:
  PricesDatabase: 
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-prices
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: date
          AttributeType: N
        - AttributeName: month
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
      TimeToLiveSpecification: 
        AttributeName: expirationDate
        Enabled: true
      GlobalSecondaryIndexes:
        - IndexName: month-index
          KeySchema:
            - AttributeName: month
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 2
            WriteCapacityUnits: 2
            